version: '3'
services:
  php-fpm:
    image: php:7.2-fpm-alpine
    container_name: php-fpm
    volumes:
      - .:/var/www/html
    ports:
      - 9000:9000

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - php-fpm
    ports:
      - 8888:8888
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf